### ISSUE TITLE
Unnecessary compare in if-statement

### ISSUE THREAD

**Issue by julian9499** [BytecodeBV/Bytecode-Website#1]
I have noticed that there is an unnecessary comparison in the if statement linked below:
https://github.com/BytecodeBV/Bytecode-Website/blob/2715f100cb986cd39a7cd0dc979cf5e51f2081bb/server/handle-post.js#L47

To optimise readability I suggest removing "=== false" and replacing it with a "!{statement}"

**Comment by lucianonooijen** [comment]
This is indeed a very messy mistake... Will fix it right away. Nice find.

**Comment by lucianonooijen** [comment]
Fixed in commit https://github.com/BytecodeBV/Bytecode-Website/commit/98bb0308708508aaed47dbd0f202324885ba5b3d
